rvm:
  - 1.9.2
before_script:
  - "cp config/database.yml.sample config/database.yml"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle install"
  - "psql -c 'create database rails_france_test;' -U postgres"
  - "bundle exec rake db:migrate db:test:prepare"
script: "bundle exec rake test:travis"
